### ISSUE TITLE
Wrong website?

### ISSUE THREAD

**Issue by thebergamo** [diegofelipece/mussum-ipsum#19]
Hey! 
Looks like your website is going to some e-commerce site? is that correcT?

**Comment by diegofelipece** [comment]
Hey @thebergamo  I had my server hkd and the mussumipsum.com DNS redirected to another IP. I'm still owning the domain, I just need to setup some stuf and the site should be back in a cuple of days. I'll close the issue when that happens :)

Tnx for letting me know.

**Comment by thebergamo** [comment]
That's fine. In case you need any assistance let me know :)

**Comment by diegofelipece** [comment]
Site is back! :)
https://mussumipsum.com/
